### ISSUE TITLE
State HW requirements more clearly

### ISSUE THREAD

**Issue by useronym** [NVlabs/instant-ngp#47]
After building the binaries, I get an error
```
Uncaught exception: Turing Tensor Core operations must be run on a machine with compute capability at least 75.
```

Upon further inspection, my GPU only supports compute version 6.1. Perhaps it's my naivete that I could run this on a GTX 1080, but I think the readme could state HW requirements more clearly, by saying that compute capability 7.5 is required.

**Comment by Tom94** [comment]
Hi there, the codebase actually runs on GTX 1000 series GPUs by now -- this error message was removed just yesterday. Pulling the latest commit should do the trick.

**Comment by useronym** [comment]
Ah, that's awesome! You are right that the above error doesn't occur anymore, however it seems like my GPU doesn't have enough memory to run the NeRF rendering tool?
```
E:\instant-ngp [master ≡]> ./build/testbed --scene data/nerf/fox
09:38:48 INFO     Loading NeRF dataset from
09:38:48 INFO       data\nerf\fox\transforms.json
09:38:48 SUCCESS  Loaded 50 images of size 1080x1920 after 0s
09:38:48 INFO       cam_aabb=[min=[1.0229,-1.33309,-0.378748], max=[2.46175,1.00721,1.41295]]
09:38:49 INFO     Loading network config from: configs\nerf\base.json
09:38:49 INFO     GridEncoding:  Nmin=16 b=1.51572 F=2 T=2^19 L=16
Warning: FullyFusedMLP is not supported for the selected architecture 61.Falling back to CutlassMLP. For maximum performance, raise the target GPU architecture to 75+.
Warning: FullyFusedMLP is not supported for the selected architecture 61.Falling back to CutlassMLP. For maximum performance, raise the target GPU architecture to 75+.
09:38:49 INFO     Density model: 3--[HashGrid]-->32--[FullyFusedMLP(neurons=64,layers=3)]-->1
09:38:49 INFO     Color model:   3--[SphericalHarmonics]-->16+16--[FullyFusedMLP(neurons=64,layers=4)]-->3
09:38:49 INFO       total_encoding_params=13074912 total_network_params=9728
09:38:50 ERROR    Uncaught exception: Could not allocate memory: CUDA Error: cudaMalloc(&rawptr, n_bytes+DEBUG_GUARD_SIZE*2) failed with error out of memory
```

**Comment by Tom94** [comment]
The amount of VRAM that you need strongly depends on the dataset in question, as well as how much of your VRAM is already occupied by the OS (large vs. small display already makes a big difference).

The bundled fox scene, with GUI, takes __7.3 GB__ on my machine, so it __should__ fit into 8 gigs... barely.

Things I'd recommend for troubleshooting:
- Check how much VRAM is reserved without testbed running to gauge how easy it is to fit in
- Check whether lowering the __testbed__ resolution helps. I just pushed a commit that allows this. You'll have to pull, recompile, and then run with `--width 1280 --height 720` to reduce memory consumption by ~500 MB.
- If the above doesn't work, try running without any GUI at all: `py scripts/run.py --scene fox`

**Comment by useronym** [comment]
I tried using even lower resolution (both app and desktop) while having 7.5GB of VRAM available, but still no luck. Maybe the fact that more modern compute capabilities are not available on my GPU leads to the program needing to use more resources?

In any case thank you very much for all the extremely quick and on-point replies, I really appreciate it! 

I will see if I can get my hands on a better GPU in the coming days. Feel free to close this issue unless you think there's a bug or something causing higher VRAM usage on my HW.

**Comment by Tom94** [comment]
Gladly! I'm close this issue to consolidate it with #36 , which also covers VRAM usage -- It's good to keep one open for discussion as well as motivation to work on reducing the memory footprint in the future.
